### PR TITLE
Fix/58/project-form-rework

### LINKED ISSUE #58: [FE Feat] Rework project submission form with configurable schema

### PR DESCRIPTION
**Pull request by AmirAgassi**
📝 [Project Form Rework #58](https://github.com/KonferCA/SPUR/issues/58)

🔍 **What's Included**
- Refactored project form to use a configurable schema in `project.ts`.
- Added `DateInput`, `SocialLinks`, and `TeamMembers` components.
- Updated `SubmitProject.tsx` to use the new form schema and components.
- Edited in custom sidebar support in the dashboard templates.

📁 Files Affected:
- `frontend/src/components/DateInput.tsx`
- `frontend/src/components/SocialLinks.tsx`
- `frontend/src/components/TeamMembers.tsx`
- `frontend/src/config/forms/project.ts`
- `frontend/src/pages/SubmitProject.tsx`

### CODE REVIEW

File: frontend/src/types/index.ts [hunk 1]
```diff
@@ -1,2 +1,2 @@
-import type { ComponentProps } from './common';
-export type { ComponentProps };
+export * from './common';
+export * from './form';
```
Comment (juancwu) [inline frontend/src/types/index.ts:2]: I know is tedious to write out everything we are exporting, but sometimes it is better to be verbose so we know exactly what is being exported and from where. This works for now but if the exports grow (more files are exporting) then we should start writing what is being exported.

**Review by juancwu — APPROVED** [review]
lgtm :+1:
