### PR TITLE
Add team member modal, redesign add button, fix backend tests, fix FE tests

### LINKED ISSUE #518: Implement a new "add team member" card button
## Description
We want to make the team member component look more modern by changing the "Add Team Member" button. 

Refer to the blocked ticket for what the component should be like. Refer to the parent ticket for detailed information.

## Blocked By
- [x] #517

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly** - if this is a refactor, add the label!
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

And lastly:
- [x] Once someone picks up this ticket, **make sure to assign it**.

### LINKED ISSUE #520: Convert the team member add form in the project creation form into a modal
## Description
On the Figma right now, when you add a team member, it expands a long ass form. Let's make this 1-1 with the Figma and make it a modal.

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly** - if this is a refactor, add the label!
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

And lastly:
- [x] Once someone picks up this ticket, **make sure to assign it**.

### LINKED ISSUE #614: Update test infrastructure for authentication and CORS
## Description
Update test infrastructure by fixing cookie paths in authentication tests, correcting request methods in `server_test.go`, and updating CORS test cases to use environment variables.

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly**.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

### LINKED ISSUE #615: Enhance ConfirmationModal component w/ additional buttons and styling
## Description
Improve the ConfirmationModal component by adding support for additional action buttons, updating styling/layout, and adding comprehensive unit tests.

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly**.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

### LINKED ISSUE #616: Improve API security and routing for company endpoints
## Description
Update API security by changing permissions checks in handleGetCompany function, adding an admin route for viewing company by ID, and improving validation messages.

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly**.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

### LINKED ISSUE #617: Refactor social media display utilities
## Description
Refactor social media display logic by adding formatSocialDisplay utility function, improving URL validation, and enhancing the SocialCard component.

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly**.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

### LINKED ISSUE #618: Implement core infrastructure for social links
## Description
Add core types and functions for social links including SocialLink struct, validation functions, and data processing utilities for both frontend and backend.

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly**.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

### LINKED ISSUE #620: Update team member API for social links support
## Description
Update team member database schema and API endpoints to support social links, including modifications to CRUD operations and request/response objects.

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly**.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

### LINKED ISSUE #623: Implement team member UI components for social links
## Description
Update frontend components to support social links, including modifying TeamMembers.tsx, enhancing SocialLinks.tsx, and adding a new TeamMemberModal component.

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly**.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

### PR DESCRIPTION
**Pull request by AmirAgassi**
## Description
1. Database Changes
- Added social_links JSONB column to the team_members table with migration script
- Added SQL function insert_question_with_input_types for better question management
- Updated database models to support the new fields

2. Backend
- Improved social links processing with validation and sanitization:
  - XSS prevention and proper URL validation
  - Platform-specific validation rules
  - Sanitization for security
- Optimized API endpoints for team member operations:
  - Added helper functions for response building
  - Better error handling with descriptive messages
  - Updated permission checks (changed PermViewAllProjects to PermAdmin)
  - Added admin route for viewing any company
- Updated cookie paths from "/api/v1/auth/verify" to "/api/v1/" for consistency

3. Frontend
- Added comprehensive social links management:
  - Platform-specific validation for Twitter, LinkedIn, Instagram, Facebook, Discord, etc.
  - Input sanitization to prevent XSS attacks
  - Centralized utility functions for consistent handling
  - New TeamMemberModal component for editing team member details
  - Updated ConfirmationModal to support additional buttons
- Added SocialCard component for displaying formatted social links
- Fixed URL prefix handling to prevent double-prefixing

4. Testing
- Updated existing tests with new social_links field
- Added tests for social link validation and processing
- Updated CORS test cases for better readability
- Added project testing helper functions

## Linked Issues
- Fixes #518 
- Fixes #520 
- Fixes #614
- Fixes #615 
- Fixes #616
- Fixes #617 
- Fixes #618 
- Fixes #620 
- Fixes #623

## Checklist
Before opening this PR, make sure the PR:
- [x] Has an **assignee or group of assignees**.
- [x] Has a **reviewer or a group of reviewers**.
- [x] Is **labelled properly**.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

Additionally, make sure that:
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

File: frontend/src/components/TeamMembers/TeamMemberModal.tsx [hunk 1]
```diff
@@ -0,0 +1,402 @@
...
+                last_name: formData.last_name,
+                title: formData.title,
+                detailed_biography: formData.detailed_biography,
+                linkedin_url: socialLinks.find(link => link.platform === SocialPlatform.LinkedIn)?.urlOrHandle || '',
+                facebook_url: socialLinks.find(link => link.platform === SocialPlatform.Facebook)?.urlOrHandle || '',
+                instagram_url: socialLinks.find(link => link.platform === SocialPlatform.Instagram)?.urlOrHandle || '',
+                x_url: socialLinks.find(link => link.platform === SocialPlatform.X)?.urlOrHandle || '',
+                bluesky_url: socialLinks.find(link => link.platform === SocialPlatform.BlueSky)?.urlOrHandle || '',
+                discord_url: socialLinks.find(link => link.platform === SocialPlatform.Discord)?.urlOrHandle || '',
+                personal_website: socialLinks.find(link => link.platform === SocialPlatform.CustomUrl)?.urlOrHandle || null,
```
Comment (juancwu) [inline frontend/src/components/TeamMembers/TeamMemberModal.tsx]: Wouldn't it be easier to save the links in a list instead of individual columns? Since team members are not as sensitive as user/account then we could store as a JSONB in the team_members table and makes this a whole lot easier?

File: frontend/src/components/TeamMembers/TeamMemberModal.tsx [hunk 2]
```diff
@@ -0,0 +1,402 @@
...
+    personal_website: string | null;
+    commitment_type: string;
+    introduction: string;
+    industry_experience: string;
+    previous_work: string;
+    resume_external_url: string;
+    resume_internal_url: string;
+    founders_agreement_external_url: string;
+    founders_agreement_internal_url: string;
+    socialLinks: SocialLink[];
```
Comment (juancwu) [inline frontend/src/components/TeamMembers/TeamMemberModal.tsx:22]: This is not included in the response payload when the questions are fetched, so is this field needed?

File: frontend/src/components/TeamMembers/TeamMemberModal.tsx [hunk 3]
```diff
@@ -0,0 +1,402 @@
...
+        if (initialData.facebook_url) socialLinks.push({ id: Math.random().toString(36).substring(2, 9), platform: SocialPlatform.Facebook, urlOrHandle: initialData.facebook_url });
+        if (initialData.instagram_url) socialLinks.push({ id: Math.random().toString(36).substring(2, 9), platform: SocialPlatform.Instagram, urlOrHandle: initialData.instagram_url });
+        if (initialData.x_url) socialLinks.push({ id: Math.random().toString(36).substring(2, 9), platform: SocialPlatform.X, urlOrHandle: initialData.x_url });
+        if (initialData.bluesky_url) socialLinks.push({ id: Math.random().toString(36).substring(2, 9), platform: SocialPlatform.BlueSky, urlOrHandle: initialData.bluesky_url });
+        if (initialData.discord_url) socialLinks.push({ id: Math.random().toString(36).substring(2, 9), platform: SocialPlatform.Discord, urlOrHandle: initialData.discord_url });
+        if (initialData.personal_website) socialLinks.push({ id: Math.random().toString(36).substring(2, 9), platform: SocialPlatform.CustomUrl, urlOrHandle: initialData.personal_website });
```
Comment (juancwu) [inline frontend/src/components/TeamMembers/TeamMemberModal.tsx]: The random id can be replaced by the randomId utility function.

File: frontend/src/components/TeamMembers/TeamMembers.tsx [hunk 4]
```diff
@@ -201,27 +231,31 @@ export const TeamMembers: React.FC<TeamMembersProps> = ({
...
-                    newMember.founderAgreementExternalUrl || '',
-                founderAgreementInternalUrl:
-                    newMember.founderAgreementInternalUrl || '',
+                linkedinUrl: socialLinks.find(link => link.platform === SocialPlatform.LinkedIn)?.urlOrHandle || '',
+                facebookUrl: socialLinks.find(link => link.platform === SocialPlatform.Facebook)?.urlOrHandle || '',
+                instagramUrl: socialLinks.find(link => link.platform === SocialPlatform.Instagram)?.urlOrHandle || '',
+                xUrl: socialLinks.find(link => link.platform === SocialPlatform.X)?.urlOrHandle || '',
+                blueskyUrl: socialLinks.find(link => link.platform === SocialPlatform.BlueSky)?.urlOrHandle || '',
+                discordUrl: socialLinks.find(link => link.platform === SocialPlatform.Discord)?.urlOrHandle || '',
+                personalWebsite: socialLinks.find(link => link.platform === SocialPlatform.CustomUrl)?.urlOrHandle || '',
```
Comment (juancwu) [inline frontend/src/components/TeamMembers/TeamMembers.tsx]: Yeah, so maybe a list stored as JSONB should be easier to manage since you are iterating anyways. The frontend should parse the json and pass it as 'socialLinks'

File: frontend/src/components/TeamMembers/TeamMembers.tsx [hunk 5]
```diff
@@ -268,307 +302,414 @@ export const TeamMembers: React.FC<TeamMembersProps> = ({
...
-                        className="flex items-center gap-3 bg-gray-50 rounded-lg p-3"
+                        className="relative bg-white rounded-lg shadow-sm border border-gray-200 w-32 h-32 p-3"
                     >
-                        {/* Avatar */}
-                        <div className="w-10 h-10 rounded-full bg-gray-300 flex items-center justify-center text-gray-600 font-medium flex-shrink-0">
-                            {[member.firstName[0], member.lastName[0]].join('')}
-                        </div>
+                        {/* Edit button */}
+                        {!member.isLoading && !disabled && !member.isAccountOwner && (
+                            <button
```
Comment (juancwu) [inline frontend/src/components/TeamMembers/TeamMembers.tsx:422]: Should add the prop `type="button"` to avoid the form being submitted.

**Review by juancwu — CHANGES_REQUESTED** [review]
Check discord, i posted a video regarding a bug in the form

**Comment by juancwu** [comment]
Screenshot 2025-02-26 at 1 16 08 PM

Please fix, we should aim for all frontend builds to pass before merging to main

File: frontend/src/utils/social-links.ts [hunk 6]
```diff
@@ -0,0 +1,199 @@
...
+  }
+}
+
+/**
+ * sanitize user input for social links to prevent xss attacks
+ * removes html tags, script tags, and other potentially harmful content
+ */
+export function sanitizeSocialInput(input: string): string {
+  // remove html tags
+  let sanitized = input.replace(/<[^>]*>/g, '');
```
[the remark this answers is not in the document]
Comment (AmirAgassi) [reply frontend/src/utils/social-links.ts]: Lowkey yeahhh if its nested like <sc<script>ript>alert('xss')</script>
It could end up like <script>alert('xss') after 1 pass just cuz it broke the regex pattern :/

File: backend/internal/v1/v1_projects/answers.go [hunk 7]
```diff
@@ -93,7 +117,7 @@ func (h *Handler) handlePatchProjectAnswer(c echo.Context) error {
 	// Parse and validate request body
 	var req PatchAnswerRequest
 	if err := c.Bind(&req); err != nil {
-		return v1_common.Fail(c, 400, "Invalid request body", err)
+		return v1_common.Fail(c, http.StatusUnauthorized, "Invalid request body", err)
```
[the remark this answers is not in the document]
Comment (AmirAgassi) [reply backend/internal/v1/v1_projects/answers.go]: Fine

File: backend/.sqlc/migrations/20250226000000_add_team_member_socials.sql
Comment (juancwu) [inline backend/.sqlc/migrations/20250226000000_add_team_member_socials.sql:1]: Can you reorder your migrations to be the last ones in the list? I am working on allowing missing migrations in development deployment so it won't be needed for PRs going into main.

**Review by juancwu — CHANGES_REQUESTED** [review]

File: backend/internal/v1/v1_projects/routes.go [hunk 8]
```diff
@@ -17,6 +18,8 @@ func SetupRoutes(g *echo.Group, s interfaces.CoreServer) {
 	))
 	// projects := g.Group("/project")
 
+	g.GET("/projects", h.handleGetProjects, middleware.Auth(s.GetDB(), permissions.PermSubmitProject))
+
```
Comment (juancwu) [inline backend/internal/v1/v1_projects/routes.go]: This handler does not get the correct title for the project since it has been moved to be the answer for the company name question. Should either use the `handleListCopmanyProjects` or update the sql query, I would honestly just use the `handleListCompanyProjects`.

You could also update the submission handler to update the project's title once everything is good to go, then there is no need to change either get/list handlers.

File: backend/internal/v1/v1_projects/questions.go [hunk 9]
```diff
@@ -4,12 +4,19 @@ import (
...
 
 	"github.com/google/uuid"
 	"github.com/labstack/echo/v4"
 )
 
+// helper function to format time, same as in v1_teams lol
+func formatTime(t int64) string {
+	return time.Unix(t, 0).Format(time.RFC3339)
+}
+
```
Comment (juancwu) [inline backend/internal/v1/v1_projects/questions.go]: I think just creating a shared utils package would be better if we are copy pasta this in different places lol

**Review by juancwu — CHANGES_REQUESTED** [review]

File: backend/internal/v1/v1_projects/routes.go (hunk 8 above)
Comment (juancwu) [reply backend/internal/v1/v1_projects/routes.go]: Where is this endpoint used in the frontend?

Comment (juancwu) [reply backend/internal/v1/v1_projects/routes.go]: why was this resolved?

Comment (AmirAgassi) [reply backend/internal/v1/v1_projects/routes.go]: Good catch, just switched to use `handleListCompanyProjects` for `/projects`

File: backend/internal/v1/v1_projects/questions.go (hunk 9 above)
Comment (AmirAgassi) [reply backend/internal/v1/v1_projects/questions.go]: Gonna sneak this into `helpers.go` lol

File: backend/internal/v1/v1_projects/questions.go [hunk 10]
```diff
@@ -90,10 +92,61 @@ func (h *Handler) handleGetQuestions(c echo.Context) error {
 		return v1_common.Fail(c, http.StatusInternalServerError, "Failed to get questions", err)
 	}
 
-	// Return questions array
+	// convert team members to proper response objects
+	teamMemberResponses := make([]v1_teams.TeamMemberResponse, 0, len(teamMembers))
+	for _, member := range teamMembers {
+		// Process thhe social links with the common helper function
```
[the remark this answers is not in the document]
Comment (AmirAgassi) [reply backend/internal/v1/v1_projects/questions.go:97]: Oops

File: backend/internal/middleware/cors.go [hunk 11]
```diff
@@ -67,6 +67,8 @@ func getCORSConfigByEnv() em.CORSConfig {
 	case common.STAGING_ENV:
 		return em.CORSConfig{
 			AllowOrigins: []string{
+				"http://localhost:5173",
+				"http://127.0.0.1:5173",
```
Comment (juancwu) [inline backend/internal/middleware/cors.go]: Can we remove this for staging and preview?

**Review by juancwu — APPROVED** [review]
lgtm
