### PR TITLE
Fix auth form validations

### LINKED ISSUE #692: Unify frontend and backend authentication form validation rules
## Description
There are still some minor bugs while logging in and registering due to the backend and frontend form validation not being 1-1 - let's review it all and make sure the validation rules are present in both.

## Reproduction
1. Try to register with a password of less than 8 characters but still valid.

## Screenshots
Image

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly**.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

And lastly:
- [x] Once someone picks up this ticket, **make sure to assign it to a developer**.

### PR DESCRIPTION
**Pull request by AmirAgassi**
## Description
Fixes inconsistency between FE/BE validation (uppercase, numbers, special characters) on both ends and updating tests to use passwords that match.

## Linked Issues
- Fixes #692 

## Testing
- Expanded `AuthForm.test.tsx`

## Reviewer Checklist
When reviewing this PR, make sure to keep the following in mind:
- This PR should not span too many unrelated tickets or changes.
  - If it does, consider breaking it up into smaller PRs.
- Is the code coverage acceptable?
- Does the preview deployment work as expected?
- Does this PR pass all tests?
- Does this PR have a clear list of issues that it closes?
- Does the code follow the style guidelines of the project?

## Author Checklist
Before opening this PR, make sure the PR:
- [x] Has an **assignee or group of assignees**.
- [x] Has a **reviewer or a group of reviewers**.
- [x] Is **labelled properly**.
- [x] Has an **assigned milestone**.

Additionally, make sure that:
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

File: backend/internal/v1/v1_auth/types.go [hunk 1]
```diff
@@ -21,8 +21,8 @@ type EmailVerifiedStatusResponse struct {
  * These define the API contract for auth-related operations.
  */
 type AuthRequest struct {
-	Email    string `json:"email" validate:"required,email"`    // user's email
-	Password string `json:"password" validate:"required,min=8"` // user's password
+	Email    string `json:"email" validate:"required,email"`                                                    // user's email
+	Password string `json:"password" validate:"required,min=8,contains_upper,contains_number,contains_special"` // user's password
```
Comment (juancwu) [inline backend/internal/v1/v1_auth/types.go:25]: This causes the login form to go through the same validation process for the password which makes errors show in the login form as well, such as "Password must contain uppercase". Is this intended and ok? I am indifferent in this since when creating an account, everyone can see what is considered a valid password.

Comment (aidantrabs) [reply backend/internal/v1/v1_auth/types.go:25]: yeah they will never not have a valid password but I guess it doesn't matter and it "unifies" FE and BE

**Review by juancwu — APPROVED** [review]
lgtm

**Review by aidantrabs — APPROVED** [review]
lgtm
