### PR TITLE
Fixed mismatched backend and frontend permissions

### LINKED ISSUE #457: Fix backend and frontend permission names being mismatched
## Description
For some reason, the backend and frontend permission names aren't 1-1 and have different names. Let's make both of these pull from a single source of truth by storing all known permission bits in a DB table.

## Screenshots
As seen in the below screenshot, the permissions are mismatched.
Image

## Checklist
Before submitting this ticket, make sure this ticket:
- [x] Is **labelled properly**.
- [x] Has the **SPUR project assigned to it**.
- [x] Has an **assigned milestone**.

And lastly:
- [x] Once someone picks up this ticket, **make sure to assign it to a developer**.

### PR DESCRIPTION
**Pull request by AmirAgassi**
## Description
Aligned permission bit positions between the frontend and backend.

## Linked Issues
- Fixes #457 

## Testing
lgtm

## Checklist
Before opening this PR, make sure the PR:
- [x] Has an assignee or group of assignees.
- [x] Has a reviewer or a group of reviewers.
- [x] Is labelled properly.
- [x] Has the SPUR project assigned to it.
- [x] Has an assigned milestone.

Additionally, make sure that:
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

File: backend/internal/permissions/permissions.go [hunk 1]
```diff
@@ -22,9 +22,11 @@ const (
 // Role-based permission sets
 const (
     PermAdmin = PermIsAdmin | PermViewAllProjects | PermReviewProjects | 
-                PermManageUsers | PermManagePermissions | PermCommentOnProjects
+                PermManageUsers | PermManagePermissions | PermCommentOnProjects |
+                PermManageInvestments
 
-    PermStartupOwner = PermSubmitProject | PermCommentOnProjects | PermManageDocuments | PermManageTeam
+    PermStartupOwner = PermSubmitProject | PermCommentOnProjects | PermManageDocuments | 
+                      PermManageTeam
```
Comment (juancwu) [inline backend/internal/permissions/permissions.go:29]: Why is this in a new line? Weird formatting lol

**Review by juancwu — APPROVED** [review]
